cmake_minimum_required(VERSION 3.24)
if(NOT IS_DIRECTORY "${SOURCE_DIR}" OR NOT DESTINATION)
    message(FATAL_ERROR "Set SOURCE_DIR and DESTINATION")
endif()
file(GLOB_RECURSE files LIST_DIRECTORIES FALSE RELATIVE "${SOURCE_DIR}" "${SOURCE_DIR}/*")
set(count 0)
foreach(path IN LISTS files)
    string(TOLOWER "${path}" lower)
    if(lower MATCHES "(^|/)([^/]*(license|licence|copying|copyright|notice|authors)[^/]*|readme[^/]*|qt_attribution\\.json)$")
        get_filename_component(directory "${path}" DIRECTORY)
        file(COPY "${SOURCE_DIR}/${path}" DESTINATION "${DESTINATION}/${directory}")
        math(EXPR count "${count} + 1")
    endif()
endforeach()
if(count EQUAL 0)
    message(FATAL_ERROR "No notices found in ${SOURCE_DIR}")
endif()
